sudo: required

services:
  - docker

language: minimal

stages:
  - install
  - static-analysis
  - build
  - release

before_script:
  - cp .env.production.dist .env
  - make set-env-production
  - make setup
  - rm docker-compose.override.yml

cache:
  directories:
    - node_modules
    - android/app/build/outputs/apk
    - .code-push

jobs:
  include:
    - stage: install
      name: Project dependencies
      script:
        - make yarn-install
    - stage: static-analysis
      name: Static analysis (ESLint and Flow)
      script:
        - make yarn-static-analysis
    - stage: build
      if: tag IS present
      name: Build Android app
      script:
        - rm -rf .cache
        - make android-prepare
        - make android-release-debug
    - stage: release
      if: tag IS present
      name: Release Android app
      script:
        - make push-prepare
        - make push-production
