sudo: required

services:
  - docker

stages:
  - install
  - static-analysis
#   - build

# install:
#   - make docker-build

before_script:
  - docker pull leg3ndz/react-native-android:latest || true
  - make setup-production
  - rm docker-compose.override.yml

script:
  - docker build --pull --cache-from leg3ndz/react-native-android:latest --tag leg3ndz/react-native-android:latest .

after_script:
  - docker images

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: install
      name: Project dependencies
      script:
        - make yarn-install
    - stage: static-analysis
      name: Static analysis (ESLint and Flow)
      script:
        - make yarn-static-analysis
    # - stage: build
    #   name: Build Android app
    #   script:
    #     - rm -rf .gradle/caches
    #     - make android-prepare
    #     - make android-release
    #     - make android-bundle
