sudo: required

services:
  - docker

language: minimal

env:
  - YOUTUBE_API_KEY=$YOUTUBE_API_KEY
  - YOUTUBE_API_STREAM_URL=$YOUTUBE_API_STREAM_URL
  - API_URL=$API_URL
  - KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD
  - CODE_PUSH_LOGIN_KEY=$CODE_PUSH_LOGIN_KEY
  - CODE_PUSH_DEPLOY_KEY=$CODE_PUSH_DEPLOY_KEY

stages:
  - install
  - static-analysis
  - build

before_script:
  - cp .env.production.dist .env
  - make setup
  - rm docker-compose.override.yml

cache:
  directories:
    - node_modules
    - packages/components/node_modules
    - packages/core/node_modules
    - packages/mobile/node_modules
    - packages/web/node_modules

jobs:
  include:
    - stage: install
      name: Project dependencies
      script:
        - make yarn-install
    - stage: static-analysis
      name: Static analysis (ESLint and Flow)
      script:
        - make yarn-static-analysis
    - stage: build
      name: Build Android app
      script:
        - rm -rf .cache
        - make android-prepare
        - make android-bundle
        - make android-release-debug
