language: android

dist: trusty

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra

before_install:
  - openssl aes-256-cbc -K $encrypted_4562a431234b_key -iv $encrypted_4562a431234b_iv
    -in android/app/app.keystore.enc -out android/app/app.keystore -d
  - nvm install 12
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - rm .env.dist
before_script:
  - yarn install

stages:
  - release

jobs:
  include:
    - stage: release
      name: Release app
      script:
        - make setup-production-env
        - make setup
        - make android-release
        - make code-push-production
