language: android
before_install:
  - nvm install 12
  - node -v
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn -v
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra

stages:
  - install
  - build
  - release

jobs:
  include:
    - stage: install
      name: Project dependencies
      script:
        - make setup-production-env
        - make setup
        - make android-release
        - make code-push-prepare
        - make code-push-production
