sudo: required

services:
  - docker

language: minimal

stages:
  - install
  - static-analysis
#   - build

# install:
#   - docker pull leg3ndz/react-native-android:latest
#   - docker save leg3ndz/react-native-android:latest | gzip > docker/react-native-android.tar.gz

before_script:
  - gzip -dc docker/react-native-android.tar.gz | docker load
  - docker images
  - rm -f .env
  - make setup-production
  - rm docker-compose.override.yml

# script:
#   - docker build --pull --cache-from leg3ndz/react-native-android:latest --tag leg3ndz/react-native-android:latest .

after_script:
  - docker images

cache:
  directories:
    - docker
    - node_modules

jobs:
  include:
    - stage: install
      name: Project dependencies
      script:
        - make yarn-install
    - stage: static-analysis
      name: Static analysis (ESLint and Flow)
      script:
        - make yarn-static-analysis
    # - stage: build
    #   name: Build Android app
    #   script:
    #     - rm -rf .gradle/caches
    #     - make android-prepare
    #     - make android-release
    #     - make android-bundle
