services:
  - docker

before_script:
  - make setup
  - make docker-build

cache:
  directories:
    - node_modules
    - website/.screenshots
    - website/public/showcase/entry

script:
  - make yarn-install
