services:
  - docker

stages:
  - setup
  - install
  - build

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: setup
      name: Setup
      script:
        - make setup-production
        - make docker-build
    - stage: install
      name: Install
      script: make yarn-install
    - stage: build
      name: Build
      script:
        - make android-prepare
        - make android-release
