services:
  - docker

stages:
  - install
  - static-analysis
  - build

install:
  - make docker-build
  - docker save react-native-android | gzip > docker/react-native-android.tar.gz

before_script:
  - make setup-production
  - rm docker-compose.override.yml
  - gzip -dc docker/react-native-android.tar.gz | docker load

cache:
  directories:
    - docker
    - node_modules

jobs:
  include:
    - stage: install
      name: Project dependencies
      script:
        - make yarn-install
    - stage: static-analysis
      name: Static analysis (ESLint and Flow)
      script:
        - make yarn-static-analysis
    - stage: build
      name: Build Android app
      script:
        - rm -rf .gradle/caches
        - make android-prepare
        - make android-release
        - make android-bundle
