version: '3'

services:
  yap:
    image: leg3ndz/react-native-android
    container_name: youtube_audio_player
    environment:
      - LOCAL_USER_ID=$USER_ID
      - YOUTUBE_API_KEY=$YOUTUBE_API_KEY
      - YOUTUBE_API_STREAM_URL=$YOUTUBE_API_STREAM_URL
      - API_URL=$API_URL
      - KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD
      - CODE_PUSH_LOGIN_KEY=$CODE_PUSH_LOGIN_KEY
      - CODE_PUSH_DEPLOY_KEY=$CODE_PUSH_DEPLOY_KEY
    ports:
      - 8081:8081
      - 3000:3000
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /app/.code-push.config:/home/stephane/.code-push.config
      - $PWD:/app
    privileged: true
